apiVersion: apps/v1
kind: Deployment
metadata:
  name: eduyou-admin-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eduyou-admin-service
  template:
    metadata:
      labels:
        app: eduyou-admin-service
    spec:
      containers:
        - name: eduyou-admin-service
          image: akshayjayachandranvv/eduyou-admin-service:latest
          ports:
            - containerPort: 4003
          env:
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: eduyou-secrets
                  key: ADMIN_PORT
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: eduyou-secrets
                  key: RABBITMQ_URL
            - name: EMAIL
              valueFrom:
                secretKeyRef:
                  name: eduyou-secrets
                  key: ADMIN_EMAIL
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: eduyou-secrets
                  key: ADMIN_PASSWORD
            - name: ID
              valueFrom:
                secretKeyRef:
                  name: eduyou-secrets
                  key: ADMIN_ID
            - name: grpcPort
              valueFrom:
                secretKeyRef:
                  name: eduyou-secrets
                  key: ADMIN_GRPC_PORT
---
apiVersion: v1
kind: Service
metadata:
  name: eduyou-admin-service
spec:
  type: ClusterIP
  selector:
    app: eduyou-admin-service
  ports:
    - protocol: TCP
      port: 4003
      targetPort: 40003