apiVersion: apps/v1
kind: Deployment
metadata:
  name: eduyou-api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eduyou-api-gateway
  template:
    metadata:
      labels:
        app: eduyou-api-gateway
    spec:
      containers:
        - name: eduyou-api-gateway
          image: akshayjayachandranvv/eduyou-api-gateway:latest
          ports:
            - containerPort: 4000
          env:
          - name: PORT
            valueFrom:
              secretKeyRef:
                name: eduyou-secrets
                key: API_GATEWAY_PORT
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: eduyou-secrets
                key: JWT_SECRET
          - name: JWT_REFRESH_SECRET
            valueFrom:
              secretKeyRef:
                name: eduyou-secrets
                key: JWT_REFRESH_SECRET
          - name: RABBITMQ_URL
            valueFrom:
              secretKeyRef:
                name: eduyou-secrets
                key: RABBITMQ_URL
          - name: NODE_ENV
            valueFrom:
              secretKeyRef:
                name: eduyou-secrets
                key: API_GATEWAY_NODE_ENV
          - name: S3_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: eduyou-secrets
                key: S3_ACCESS_KEY
          - name: S3_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: eduyou-secrets
                key: S3_SECRET_ACCESS_KEY    
          - name: S3_BUCKET_REGION
            valueFrom:
              secretKeyRef:
                name: eduyou-secrets
                key: S3_BUCKET_REGION 
          - name: S3_BUCKET_NAME
            valueFrom:
              secretKeyRef:
                name: eduyou-secrets
                key: S3_BUCKET_NAME    
---
apiVersion: v1
kind: Service
metadata:
  name: eduyou-api-gateway-service
spec:
  type: NodePort
  selector:
    app: eduyou-api-gateway
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 4000
    nodePort: 32000