apiVersion: apps/v1
kind: Deployment
metadata:
  name: eduyou-chat-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eduyou-chat-service
  template:
    metadata:
      labels:
        app: eduyou-chat-service
    spec:
      containers:
        - name: eduyou-chat-service
          image: akshayjayachandranvv/eduyou-chat-service:latest
          ports:
            - containerPort: 4007
          env:
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: eduyou-secrets
                  key: CHAT_PORT
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: eduyou-secrets
                  key: RABBITMQ_URL
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: eduyou-secrets
                  key: CHAT_DB_URL
---
apiVersion: v1
kind: Service
metadata:
  name: eduyou-chat-service
spec:
  type: ClusterIP
  selector:
    app: eduyou-chat-service
  ports:
    - protocol: TCP
      port: 4007
      targetPort: 40007