apiVersion: apps/v1
kind: Deployment
metadata:
  name: eduyou-course-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eduyou-course-service
  template:
    metadata:
      labels:
        app: eduyou-course-service
    spec:
      containers:
        - name: eduyou-course-service
          image: akshayjayachandranvv/eduyou-course-service:latest
          ports:
            - containerPort: 4001
          env:
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: eduyou-secrets
                  key: COURSE_PORT
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: eduyou-secrets
                  key: RABBITMQ_URL
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef: 
                  name: eduyou-secrets
                  key: COURSE_DB_URL
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: eduyou-secrets
                  key: S3_ACCESS_KEY
            - name: S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: eduyou-secrets
                  key: S3_SECRET_ACCESS_KEY
            - name: S3_BUCKET_REGION
              valueFrom:
                secretKeyRef:
                  name: eduyou-secrets
                  key: S3_BUCKET_REGION
            - name: S3_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: eduyou-secrets
                  key: S3_BUCKET_NAME
---
apiVersion: v1
kind: Service
metadata:
  name: eduyou-course-service
spec:
  type: ClusterIP
  selector:
    app: eduyou-course-service
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 40001