apiVersion: apps/v1
kind: Deployment
metadata:
  name: eduyou-order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eduyou-order-service
  template:
    metadata:
      labels:
        app: eduyou-order-service
    spec:
      containers:
        - name: eduyou-order-service
          image: akshayjayachandranvv/eduyou-order-service:latest
          ports:
            - containerPort: 4006
          env:
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: eduyou-secrets
                  key: ORDER_PORT
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: eduyou-secrets
                  key: RABBITMQ_URL
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: eduyou-secrets
                  key: ORDER_DB_URL
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: eduyou-secrets
                  key: STRIPE_SECRET_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: eduyou-order-service
spec:
  type: ClusterIP
  selector:
    app: eduyou-order-service
  ports:
    - protocol: TCP
      port: 4006
      targetPort: 40006