apiVersion: apps/v1
kind: Deployment
metadata:
  name: eduyou-tutor-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eduyou-tutor-service
  template:
    metadata:
      labels:
        app: eduyou-tutor-service
    spec:
      containers:
        - name: eduyou-tutor-service
          image: akshayjayachandranvv/eduyou-tutor-service:latest
          ports:
            - containerPort: 4002
          env:
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: eduyou-secrets
                  key: TUTOR_PORT
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: eduyou-secrets
                  key: RABBITMQ_URL
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: eduyou-secrets
                  key: TUTOR_DB_URL
            - name: EMAIL
              valueFrom:
                secretKeyRef:
                  name: eduyou-secrets
                  key: EMAIL
            - name: EMAIL_PASS
              valueFrom:
                secretKeyRef:
                  name: eduyou-secrets
                  key: EMAIL_PASS
            - name: grpcPort
              valueFrom:
                secretKeyRef:
                  name: eduyou-secrets
                  key: TUTOR_GRPC_PORT
---
apiVersion: v1
kind: Service
metadata:
  name: eduyou-tutor-service
spec:
  type: ClusterIP
  selector:
    app: eduyou-tutor-service
  ports:
    - protocol: TCP
      port: 4002
      targetPort: 40002