apiVersion: apps/v1
kind: Deployment
metadata:
  name: eduyou-user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eduyou-user-service
  template:
    metadata:
      labels:
        app: eduyou-user-service
    spec:
      containers:
        - name: eduyou-user-service
          image: akshayjayachandranvv/eduyou-user-service:latest
          ports:
            - containerPort: 40001
          env:
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: eduyou-secrets
                  key: USER_PORT
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: eduyou-secrets
                  key: RABBITMQ_URL
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: eduyou-secrets
                  key: USER_DB_URL
            - name: EMAIL
              valueFrom:
                secretKeyRef:
                  name: eduyou-secrets
                  key: EMAIL
            - name: EMAIL_PASS
              valueFrom:
                secretKeyRef:
                  name: eduyou-secrets
                  key: EMAIL_PASS
            - name: GOOGLE_CLIENTID
              valueFrom:
                secretKeyRef:
                  name: eduyou-secrets
                  key: GOOGLE_CLIENTID
            - name: grpcPort
              valueFrom:
                secretKeyRef:
                  name: eduyou-secrets
                  key: USER_GRPC_PORT
---
apiVersion: v1
kind: Service
metadata:
  name: eduyou-user-service
spec:
  type: ClusterIP
  selector:
    app: eduyou-user-service
  ports:
    - protocol: TCP
      port: 40001
      targetPort: 40001